services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - ORACLE_PASSWORD=ThisPassW0rd12!
      - ORACLE_HOST=oracle 
      - ORACLE_USER=system 
      - ORACLE_SERVICE_NAME=FREEPDB1 
      - ORACLE_PORT=1521
  db:
    image: gvenzl/oracle-xe
    ports:
      - "1521:1521"
    environment:
      - ORACLE_PASSWORD=ThisPassW0rd12!
    healthcheck:
      test: ["CMD", "healthcheck.sh"]
      interval: 10s   
      timeout: 5s   
      retries: 5
